name: flutter_weather_bloc_app
description: "A well-structured weather application using the BLoC pattern."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0 # Though we will mock the data, this is what you'd use.
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2 # Added for local storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

